//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpensesEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GastoCompartido
    {
        public int idGastoCompartido { get; set; }
        public int idGasto1 { get; set; }
        public int idGasto2 { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal precio { get; set; }
    
        public virtual Gasto Gasto { get; set; }
        public virtual Gasto Gasto1 { get; set; }
    }
}
