//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpensesEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gasto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gasto()
        {
            this.GastoCompartido = new HashSet<GastoCompartido>();
            this.GastoCompartido1 = new HashSet<GastoCompartido>();
        }
    
        public int idGasto { get; set; }
        public string idUserGasto { get; set; }
        public int idTipoGasto { get; set; }
        public string Concepto { get; set; }
        public decimal Precio { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> idTipoPago { get; set; }
        public Nullable<int> idGrupoGasto { get; set; }
        public Nullable<int> idTipoMoneda { get; set; }
        public Nullable<int> GastoComputable { get; set; }
        public Nullable<bool> GastoRecurrente { get; set; }
        public Nullable<bool> Resaltar { get; set; }
        public Nullable<bool> GastoEditable { get; set; }
        public Nullable<int> idSubTipoGasto { get; set; }
        public Nullable<bool> EsRegalo { get; set; }
        public Nullable<bool> EsCompartido { get; set; }
        public Nullable<int> Valoracion { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Gasto Gasto1 { get; set; }
        public virtual Gasto Gasto2 { get; set; }
        public virtual GrupoGasto GrupoGasto { get; set; }
        public virtual SubTipoGasto SubTipoGasto { get; set; }
        public virtual TipoGasto TipoGasto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GastoCompartido> GastoCompartido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GastoCompartido> GastoCompartido1 { get; set; }
    }
}
