//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpensesEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Idiomas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Idiomas()
        {
            this.GrupoGastoTextosTraduccion = new HashSet<GrupoGastoTextosTraduccion>();
            this.PeriocidadTextosTraduccion = new HashSet<PeriocidadTextosTraduccion>();
            this.SubTipoGastoTextosTraduccion = new HashSet<SubTipoGastoTextosTraduccion>();
            this.TextosVarios = new HashSet<TextosVarios>();
            this.TipoGastoTextosTraduccion = new HashSet<TipoGastoTextosTraduccion>();
            this.TipoPagoTextosTraduccion = new HashSet<TipoPagoTextosTraduccion>();
            this.ValuesDefaultConcepto = new HashSet<ValuesDefaultConcepto>();
        }
    
        public int idIdioma { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public string culture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrupoGastoTextosTraduccion> GrupoGastoTextosTraduccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PeriocidadTextosTraduccion> PeriocidadTextosTraduccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubTipoGastoTextosTraduccion> SubTipoGastoTextosTraduccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TextosVarios> TextosVarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoGastoTextosTraduccion> TipoGastoTextosTraduccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoPagoTextosTraduccion> TipoPagoTextosTraduccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValuesDefaultConcepto> ValuesDefaultConcepto { get; set; }
        public virtual ValuesEnvioEmail ValuesEnvioEmail { get; set; }
    }
}
