//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpensesEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubTipoGasto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubTipoGasto()
        {
            this.Gasto = new HashSet<Gasto>();
            this.SubTipoGastoTextosTraduccion = new HashSet<SubTipoGastoTextosTraduccion>();
            this.SummaryPorSubTipoGasto_Mensual = new HashSet<SummaryPorSubTipoGasto_Mensual>();
            this.SummaryPorSubTipoGasto = new HashSet<SummaryPorSubTipoGasto>();
            this.ValuesDefaultConcepto = new HashSet<ValuesDefaultConcepto>();
        }
    
        public int idSubTipoGasto { get; set; }
        public int idTipoGasto { get; set; }
        public string Nombre { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gasto> Gasto { get; set; }
        public virtual TipoGasto TipoGasto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubTipoGastoTextosTraduccion> SubTipoGastoTextosTraduccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SummaryPorSubTipoGasto_Mensual> SummaryPorSubTipoGasto_Mensual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SummaryPorSubTipoGasto> SummaryPorSubTipoGasto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValuesDefaultConcepto> ValuesDefaultConcepto { get; set; }
    }
}
