//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpensesEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sueldo
    {
        public string idUserGasto { get; set; }
        public Nullable<decimal> SueldoBrutoAnual { get; set; }
        public Nullable<decimal> SueldoNetoEnero { get; set; }
        public Nullable<decimal> SueldoNetoFebrero { get; set; }
        public Nullable<decimal> SueldoNetoMarzo { get; set; }
        public Nullable<decimal> SueldoNetoAbril { get; set; }
        public Nullable<decimal> SueldoNetoMayo { get; set; }
        public Nullable<decimal> SueldoNetoJunio { get; set; }
        public Nullable<decimal> SueldoNetoJulio { get; set; }
        public Nullable<decimal> SueldoNetoAgosto { get; set; }
        public Nullable<decimal> SueldoNetoSeptiembre { get; set; }
        public Nullable<decimal> SueldoNetoOctubre { get; set; }
        public Nullable<decimal> SueldoNetoNoviembre { get; set; }
        public Nullable<decimal> SueldoNetoDiciembre { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
