//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpensesEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoGasto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoGasto()
        {
            this.Gasto = new HashSet<Gasto>();
            this.GastoRecurrente = new HashSet<GastoRecurrente>();
            this.SubTipoGasto = new HashSet<SubTipoGasto>();
            this.SummaryPorTipoGasto = new HashSet<SummaryPorTipoGasto>();
            this.SummaryPorTipoGasto_Mensual = new HashSet<SummaryPorTipoGasto_Mensual>();
            this.TipoGastoTextosTraduccion = new HashSet<TipoGastoTextosTraduccion>();
        }
    
        public int idTipoGasto { get; set; }
        public string Nombre { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gasto> Gasto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GastoRecurrente> GastoRecurrente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubTipoGasto> SubTipoGasto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SummaryPorTipoGasto> SummaryPorTipoGasto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SummaryPorTipoGasto_Mensual> SummaryPorTipoGasto_Mensual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoGastoTextosTraduccion> TipoGastoTextosTraduccion { get; set; }
    }
}
