//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpensesEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValuesEnvioEmail
    {
        public int id { get; set; }
        public string idUser { get; set; }
        public Nullable<bool> EnvioMail { get; set; }
        public Nullable<bool> TotalGastadoMesAnterior { get; set; }
        public Nullable<bool> AhorroMesAnterior { get; set; }
        public Nullable<bool> RegalosMesAnterior { get; set; }
        public Nullable<int> idIdiomaEMail { get; set; }
        public string Header { get; set; }
    
        public virtual Idiomas Idiomas { get; set; }
    }
}
