//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpensesEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vst_InOut
    {
        public string idUserGasto { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Descripcion { get; set; }
        public int idIdioma { get; set; }
        public Nullable<int> IdIdiomaSubTipo { get; set; }
        public string Concepto { get; set; }
        public int idGasto { get; set; }
        public decimal Precio { get; set; }
        public string InOut { get; set; }
        public Nullable<bool> GastoRecurrente { get; set; }
        public Nullable<bool> Resaltar { get; set; }
        public Nullable<bool> GastoEditable { get; set; }
        public string Descripcion_Subtipo { get; set; }
    }
}
