//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpensesEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vst_Export_Gastos
    {
        public string idUserGasto { get; set; }
        public string GrupoGasto { get; set; }
        public string TipoGasto { get; set; }
        public string SubTipoGasto { get; set; }
        public string Concepto { get; set; }
        public decimal Importe { get; set; }
        public System.DateTime Fecha { get; set; }
        public string EsRegalo { get; set; }
        public string Tipo_Pago { get; set; }
    }
}
