//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace expenses.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Descripciones {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Descripciones() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("expenses.Resources.Descripciones", typeof(Descripciones).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a a.
        /// </summary>
        public static string a {
            get {
                return ResourceManager.GetString("a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pequeña web de gestión de gastos mensuales..
        /// </summary>
        public static string AboutDescripcion {
            get {
                return ResourceManager.GetString("AboutDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abril.
        /// </summary>
        public static string Abril {
            get {
                return ResourceManager.GetString("Abril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gasto activo.
        /// </summary>
        public static string AddGastoActivo {
            get {
                return ResourceManager.GetString("AddGastoActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gasto computable.
        /// </summary>
        public static string AddGastoComputable {
            get {
                return ResourceManager.GetString("AddGastoComputable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Concepto.
        /// </summary>
        public static string AddGastoConcepto {
            get {
                return ResourceManager.GetString("AddGastoConcepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string AddGastoFecha {
            get {
                return ResourceManager.GetString("AddGastoFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gasto Compartido?.
        /// </summary>
        public static string AddGastoGastoCompartido {
            get {
                return ResourceManager.GetString("AddGastoGastoCompartido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string AddGastoGastoCompartidoPersona {
            get {
                return ResourceManager.GetString("AddGastoGastoCompartidoPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo Gasto.
        /// </summary>
        public static string AddGastoGrupoGasto {
            get {
                return ResourceManager.GetString("AddGastoGrupoGasto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo Gasto por defecto.
        /// </summary>
        public static string AddGastoGrupoGastodefecto {
            get {
                return ResourceManager.GetString("AddGastoGrupoGastodefecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importe.
        /// </summary>
        public static string AddGastoImporte {
            get {
                return ResourceManager.GetString("AddGastoImporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Periodicidad.
        /// </summary>
        public static string AddGastoPeriodicidad {
            get {
                return ResourceManager.GetString("AddGastoPeriodicidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subtipo gasto.
        /// </summary>
        public static string AddGastoSubTipoGasto {
            get {
                return ResourceManager.GetString("AddGastoSubTipoGasto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo gasto.
        /// </summary>
        public static string AddGastoTipoGasto {
            get {
                return ResourceManager.GetString("AddGastoTipoGasto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TipoMoneda.
        /// </summary>
        public static string AddGastoTipoMoneda {
            get {
                return ResourceManager.GetString("AddGastoTipoMoneda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Pago.
        /// </summary>
        public static string AddGastoTipoPago {
            get {
                return ResourceManager.GetString("AddGastoTipoPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valoración.
        /// </summary>
        public static string AddGastoValoracion {
            get {
                return ResourceManager.GetString("AddGastoValoracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agosto.
        /// </summary>
        public static string Agosto {
            get {
                return ResourceManager.GetString("Agosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ahorro mensual previsto:.
        /// </summary>
        public static string AhorroMensualPrevisto {
            get {
                return ResourceManager.GetString("AhorroMensualPrevisto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir.
        /// </summary>
        public static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string btnEliminar {
            get {
                return ResourceManager.GetString("btnEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar gráfico.
        /// </summary>
        public static string btnGenerarGrafico {
            get {
                return ResourceManager.GetString("btnGenerarGrafico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar.
        /// </summary>
        public static string btnModificar {
            get {
                return ResourceManager.GetString("btnModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acceptar.
        /// </summary>
        public static string btnOK {
            get {
                return ResourceManager.GetString("btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        public static string btnUpdate {
            get {
                return ResourceManager.GetString("btnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        public static string btnVolver {
            get {
                return ResourceManager.GetString("btnVolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estilo del gráfico.
        /// </summary>
        public static string CharEstiloGrafico {
            get {
                return ResourceManager.GetString("CharEstiloGrafico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de gráfico a generar.
        /// </summary>
        public static string ChartTipoGrafico {
            get {
                return ResourceManager.GetString("ChartTipoGrafico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Columnas.
        /// </summary>
        public static string ChartTypeBarras {
            get {
                return ResourceManager.GetString("ChartTypeBarras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quesitos.
        /// </summary>
        public static string ChartTypePie {
            get {
                return ResourceManager.GetString("ChartTypePie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diciembre.
        /// </summary>
        public static string Diciembre {
            get {
                return ResourceManager.GetString("Diciembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enero.
        /// </summary>
        public static string Enero {
            get {
                return ResourceManager.GetString("Enero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es un regalo?.
        /// </summary>
        public static string EsRegalo {
            get {
                return ResourceManager.GetString("EsRegalo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar a Excel los datos del año actual....
        /// </summary>
        public static string Exportxls {
            get {
                return ResourceManager.GetString("Exportxls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Febrero.
        /// </summary>
        public static string Febrero {
            get {
                return ResourceManager.GetString("Febrero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gasto mes actual:.
        /// </summary>
        public static string GastoMensual {
            get {
                return ResourceManager.GetString("GastoMensual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gasto mensual periódico:.
        /// </summary>
        public static string GastoMensualPeriodico {
            get {
                return ResourceManager.GetString("GastoMensualPeriodico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Próximo recibo tarjeta crédito:.
        /// </summary>
        public static string GastoMensualTarjeta {
            get {
                return ResourceManager.GetString("GastoMensualTarjeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gasto del 20 del mes anterior al 20 del mes actual hecho con tarjeta de crédito.
        /// </summary>
        public static string GastoMensualTarjetaExplicacion {
            get {
                return ResourceManager.GetString("GastoMensualTarjetaExplicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gasto mes anterior:.
        /// </summary>
        public static string GastoMesAnterior {
            get {
                return ResourceManager.GetString("GastoMesAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gráfico acumulado año actual.
        /// </summary>
        public static string GraficoAnyoActual {
            get {
                return ResourceManager.GetString("GraficoAnyoActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gráfico mes actual.
        /// </summary>
        public static string GraficoMesActual {
            get {
                return ResourceManager.GetString("GraficoMesActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Concepto.
        /// </summary>
        public static string GridGastoConcepto {
            get {
                return ResourceManager.GetString("GridGastoConcepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string GridGastoFecha {
            get {
                return ResourceManager.GetString("GridGastoFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (€).
        /// </summary>
        public static string GridGastoImporte {
            get {
                return ResourceManager.GetString("GridGastoImporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Texto a buscar.
        /// </summary>
        public static string GridTextoABuscar {
            get {
                return ResourceManager.GetString("GridTextoABuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Gasto.
        /// </summary>
        public static string GridTipoGasto {
            get {
                return ResourceManager.GetString("GridTipoGasto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expenses es una aplicación de gestión de gastos adaptada a dispositivos móviles y de fácil uso. .
        /// </summary>
        public static string HomeNoAutentificadoLinea1 {
            get {
                return ResourceManager.GetString("HomeNoAutentificadoLinea1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facilidad para gestionar sus gastos con muy pocos clicks.  Podrá  categorizar un gasto entre sus diferentes tipos, añadirlo a un grupo de gasto....y desde cualquier lugar. Jamás registrar un gasto había sido tan fácil. Además, existe la opción de programar gastos mensuales, anuales....
        /// </summary>
        public static string HomeNoAutentificadoTextoGrupo1 {
            get {
                return ResourceManager.GetString("HomeNoAutentificadoTextoGrupo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Posibilidad de generar gráficos con lo gastos del mes y del año de una manera sencilla. Así podrá saber, en todo momento y de forma gráfica, en qué se ha gastado el dinero..
        /// </summary>
        public static string HomeNoAutentificadoTextoGrupo2 {
            get {
                return ResourceManager.GetString("HomeNoAutentificadoTextoGrupo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expenses, a partir de sus gastos programados y de un potente motor de IA le ofrece la posibilidad de ver una previsión de gastos..
        /// </summary>
        public static string HomeNoAutentificadoTextoGrupo3 {
            get {
                return ResourceManager.GetString("HomeNoAutentificadoTextoGrupo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gastos.
        /// </summary>
        public static string HomeNoAutentificadoTituloGrupo1 {
            get {
                return ResourceManager.GetString("HomeNoAutentificadoTituloGrupo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creación de gráficos.
        /// </summary>
        public static string HomeNoAutentificadoTituloGrupo2 {
            get {
                return ResourceManager.GetString("HomeNoAutentificadoTituloGrupo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Previsión Gastos.
        /// </summary>
        public static string HomeNoAutentificadoTituloGrupo3 {
            get {
                return ResourceManager.GetString("HomeNoAutentificadoTituloGrupo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir nuevo gasto.
        /// </summary>
        public static string ImgNewGasto {
            get {
                return ResourceManager.GetString("ImgNewGasto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir nuevo gasto periódico.
        /// </summary>
        public static string ImgNewGastoRecurrente {
            get {
                return ResourceManager.GetString("ImgNewGastoRecurrente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver gráficos.
        /// </summary>
        public static string ImgStats {
            get {
                return ResourceManager.GetString("ImgStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Julio.
        /// </summary>
        public static string Julio {
            get {
                return ResourceManager.GetString("Julio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Junio.
        /// </summary>
        public static string Junio {
            get {
                return ResourceManager.GetString("Junio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;br/&gt;El total ahorrado el mes anterior es: &lt;b&gt;{0} &lt;/b&gt;€. &amp;nbsp;.
        /// </summary>
        public static string mailAhorroMesAnterior {
            get {
                return ResourceManager.GetString("mailAhorroMesAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;br/&gt;&lt;br/&gt;En lo referente al ahorro mensual, este mes según el ahorro definido en Expenses no has ahorrado nada, aunque tampoco ha bajado tu cuenta corriente. Hay que reconocerlo, tiene su mérito ajustarse tanto..
        /// </summary>
        public static string mailAhorroMesIgual {
            get {
                return ResourceManager.GetString("mailAhorroMesIgual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;br/&gt;&lt;br/&gt;En lo referente al ahorro mensual, este mes según el ahorro definido en Expenses has conseguido ahorrar &lt;b&gt;{0}€&lt;/b&gt;..
        /// </summary>
        public static string mailAhorroMesMayor {
            get {
                return ResourceManager.GetString("mailAhorroMesMayor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;nbsp; Además el pasado mes de {0} también ahorraste {1}..
        /// </summary>
        public static string mailAhorroMesMayorY2MesesMayor {
            get {
                return ResourceManager.GetString("mailAhorroMesMayorY2MesesMayor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;nbsp; Además has conseguido ahorrar después que el pasado {0} gastaste &lt;b&gt;{1}€&lt;/b&gt; de más. Felicidades, hay que seguir en esta dirección puesto que has pasado de no ahorrar, a ahorrar..
        /// </summary>
        public static string mailAhorroMesMayorY2MesesMenorOIgual {
            get {
                return ResourceManager.GetString("mailAhorroMesMayorY2MesesMenorOIgual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;br/&gt;&lt;br/&gt;En lo referente al ahorro mensual, este mes según el ahorro definido en Expenses no has ahorrado nada. De hecho, has gastado &lt;b&gt;{0}€&lt;/b&gt; más de lo ingresado..
        /// </summary>
        public static string mailAhorroMesMenor {
            get {
                return ResourceManager.GetString("mailAhorroMesMenor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;nbsp; Encima has pasado de estar ahorrando, a no ahorrar ya que hace 2 meses sí que ahorraste..
        /// </summary>
        public static string mailAhorroMesMenorY2MesesMayor {
            get {
                return ResourceManager.GetString("mailAhorroMesMenorY2MesesMayor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;nbsp; Encima, llevas como mínimo 2 meses que no ahorras. Habría que hacer un pequeño esfuerzo y cambiar esta tendencia..
        /// </summary>
        public static string mailAhorroMesMenorY2MesesMenorOIgual {
            get {
                return ResourceManager.GetString("mailAhorroMesMenorY2MesesMenorOIgual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;br/&gt;&lt;br/&gt; Este email ha sido generado automáticamente. Por favor, no responda a este email..
        /// </summary>
        public static string mailBottom {
            get {
                return ResourceManager.GetString("mailBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Curiosamente, este mes tu gasto ha sido el mismo que el gasto medio mensual de todo el año..
        /// </summary>
        public static string mailGastoMedioMensualIgualMedia {
            get {
                return ResourceManager.GetString("mailGastoMedioMensualIgualMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teniendo en cuenta que tu gasto medio mensual es de &lt;b&gt;{0}€&lt;/b&gt;, este mes has gastado &lt;b&gt;{1}€ &lt;/b&gt; más, un &lt;b&gt;{2}% &lt;/b&gt; por encima de la media mensual..
        /// </summary>
        public static string mailGastoMedioMensualMayorMedia {
            get {
                return ResourceManager.GetString("mailGastoMedioMensualMayorMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teniendo en cuenta que tu gasto medio mensual es de &lt;b&gt;{0}€&lt;/b&gt;, este mes pasado has gastado &lt;b&gt;{1}€ &lt;/b&gt; menos, estando un &lt;b&gt; {2}%&lt;/b&gt; por debajo  la media mensual..
        /// </summary>
        public static string mailGastoMedioMensualMenorMedia {
            get {
                return ResourceManager.GetString("mailGastoMedioMensualMenorMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Increiblemente, respecto el gasto de hace dos meses has gastado lo mismo. .
        /// </summary>
        public static string mailGastoRespecto2MesesAtrasIgual {
            get {
                return ResourceManager.GetString("mailGastoRespecto2MesesAtrasIgual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esto ha supuesto un incremento del gasto en &lt;b&gt;{0}€ &lt;/b&gt;respecto {2}  (aproximadamente un &lt;b&gt;{1}% más&lt;/b&gt;). .
        /// </summary>
        public static string mailGastoRespecto2MesesAtrasMas {
            get {
                return ResourceManager.GetString("mailGastoRespecto2MesesAtrasMas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esto ha supuesto un decremento del gasto en &lt;b&gt;{0}€  &lt;/b&gt;respecto  {2} (aproximadamente un &lt;b&gt; {1}% menos&lt;/b&gt;)..
        /// </summary>
        public static string mailGastoRespecto2MesesAtrasMenos {
            get {
                return ResourceManager.GetString("mailGastoRespecto2MesesAtrasMenos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;br/&gt;Sobre este total, tenemos {0} grupos de gastos diferentes:&amp;nbsp;.
        /// </summary>
        public static string mailGrupoGastos {
            get {
                return ResourceManager.GetString("mailGrupoGastos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;nbsp;y el resto (&lt;b&gt;{0}€&lt;/b&gt;). &lt;br/&gt;.
        /// </summary>
        public static string mailGrupoGastosResto {
            get {
                return ResourceManager.GetString("mailGrupoGastosResto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apreciado/a&amp;nbsp;&lt;b&gt;{0}&lt;/b&gt;: &lt;br/&gt;.
        /// </summary>
        public static string mailLinea1 {
            get {
                return ResourceManager.GetString("mailLinea1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a De momento, este mes de {0} es el mes que más has gastado en todo el año..
        /// </summary>
        public static string mailMaximoGastadoporMes {
            get {
                return ResourceManager.GetString("mailMaximoGastadoporMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este mes no has realizado ningún gasto..
        /// </summary>
        public static string mailNoGasto {
            get {
                return ResourceManager.GetString("mailNoGasto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;br/&gt;Ningún gasto ha sido asociado a algún grupo de gasto concreto.&lt;br/&gt;.
        /// </summary>
        public static string mailNoGrupoGasto {
            get {
                return ResourceManager.GetString("mailNoGrupoGasto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;br/&gt;El total gastado en regalos  del mes anterior es: &lt;b&gt;{0}&lt;/b&gt;€.&amp;nbsp;.
        /// </summary>
        public static string mailRegaloMesAnterior {
            get {
                return ResourceManager.GetString("mailRegaloMesAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expenses: Resumen de actividad mensual.
        /// </summary>
        public static string mailSubject {
            get {
                return ResourceManager.GetString("mailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;br&gt;&lt;br&gt;Respecto a los diferentes tipos de gastos de {0}, estos han sido (% aproximado): &lt;br&gt;&lt;br&gt;.
        /// </summary>
        public static string mailTipoGastoCabecera {
            get {
                return ResourceManager.GetString("mailTipoGastoCabecera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;br/&gt;Para finalizar, indicarte que el total gastado durante el presente año es de &lt;b&gt;{0}€&lt;/b&gt;..
        /// </summary>
        public static string mailTotalGastado {
            get {
                return ResourceManager.GetString("mailTotalGastado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para finalizar, indicarte que has conseguido mantener el mismo gasto acumulado que el año pasado, siendo los dos de {0} €..
        /// </summary>
        public static string mailTotalGastadoAnyoAnteriorIgual {
            get {
                return ResourceManager.GetString("mailTotalGastadoAnyoAnteriorIgual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;br/&gt;Para finalizar, indicarte que el total gastado durante el presente año es de &lt;b&gt;{0}€&lt;/b&gt; mientras que el año pasado, por esta fechas, el gasto era de &lt;b&gt;{1}€ &lt;/b&gt; (&lt;b&gt;{2}€&lt;/b&gt; más)..
        /// </summary>
        public static string mailTotalGastadoAnyoAnteriorMas {
            get {
                return ResourceManager.GetString("mailTotalGastadoAnyoAnteriorMas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;br/&gt;Para finalizar, indicarte que el total gastado durante el presente año es de &lt;b&gt;{0}€&lt;/b&gt; mientras que el año pasado, por esta fechas, el gasto era de &lt;b&gt;{1}€ &lt;/b&gt; (&lt;b&gt;{2}€&lt;/b&gt; menos)..
        /// </summary>
        public static string mailTotalGastadoAnyoAnteriorMenos {
            get {
                return ResourceManager.GetString("mailTotalGastadoAnyoAnteriorMenos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;br/&gt;El total gastado durante {0} ha sido de &lt;b&gt;{1}&lt;/b&gt;€.&amp;nbsp;.
        /// </summary>
        public static string mailTotalGastadoMesAnterior {
            get {
                return ResourceManager.GetString("mailTotalGastadoMesAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar la configuración de la cuenta.
        /// </summary>
        public static string ManageCambiarConf {
            get {
                return ResourceManager.GetString("ManageCambiarConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar la contraseña.
        /// </summary>
        public static string ManageChangePassword {
            get {
                return ResourceManager.GetString("ManageChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver.
        /// </summary>
        public static string ManageChangeSueldo {
            get {
                return ResourceManager.GetString("ManageChangeSueldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear password.
        /// </summary>
        public static string ManageCreatePassword {
            get {
                return ResourceManager.GetString("ManageCreatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Colores para gastos periódicos.
        /// </summary>
        public static string ManageEnableColorGastoRecurrenteGrid {
            get {
                return ResourceManager.GetString("ManageEnableColorGastoRecurrenteGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver gastos incluídos los periódicos.
        /// </summary>
        public static string ManageEnableVerSinGastosRecurrentes {
            get {
                return ResourceManager.GetString("ManageEnableVerSinGastosRecurrentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Habilitar % sobre mes anterior.
        /// </summary>
        public static string ManageEnableVerTpcvsMesAnterior {
            get {
                return ResourceManager.GetString("ManageEnableVerTpcvsMesAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi Perfil.
        /// </summary>
        public static string ManageMiPerfil {
            get {
                return ResourceManager.GetString("ManageMiPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string ManagePassword {
            get {
                return ResourceManager.GetString("ManagePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión económica.
        /// </summary>
        public static string ManageSueldos {
            get {
                return ResourceManager.GetString("ManageSueldos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marzo.
        /// </summary>
        public static string Marzo {
            get {
                return ResourceManager.GetString("Marzo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mayo.
        /// </summary>
        public static string Mayo {
            get {
                return ResourceManager.GetString("Mayo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión económica.
        /// </summary>
        public static string ModalDineroTitulo {
            get {
                return ResourceManager.GetString("ModalDineroTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir gasto periódico.
        /// </summary>
        public static string ModalGastoRecurrenteTitulo {
            get {
                return ResourceManager.GetString("ModalGastoRecurrenteTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificación de gastos periódicos.
        /// </summary>
        public static string ModalGastoRecurrenteTituloEdit {
            get {
                return ResourceManager.GetString("ModalGastoRecurrenteTituloEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;?.
        /// </summary>
        public static string msgEliminarDelFin {
            get {
                return ResourceManager.GetString("msgEliminarDelFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro de querer eliminar el gasto &quot;.
        /// </summary>
        public static string msgEliminarDelInicio {
            get {
                return ResourceManager.GetString("msgEliminarDelInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expenses v1.0.
        /// </summary>
        public static string MyApp {
            get {
                return ResourceManager.GetString("MyApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acerca de.
        /// </summary>
        public static string MyAppAcercaDe {
            get {
                return ResourceManager.GetString("MyAppAcercaDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        public static string MyAppContacto {
            get {
                return ResourceManager.GetString("MyAppContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string MyAppIniciarSession {
            get {
                return ResourceManager.GetString("MyAppIniciarSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        public static string MyAppInicio {
            get {
                return ResourceManager.GetString("MyAppInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        public static string MyAppRegistrarse {
            get {
                return ResourceManager.GetString("MyAppRegistrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar un gasto.
        /// </summary>
        public static string myModalDelGastoTitle {
            get {
                return ResourceManager.GetString("myModalDelGastoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar un gasto periódico.
        /// </summary>
        public static string myModalDelTitle {
            get {
                return ResourceManager.GetString("myModalDelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver un gasto.
        /// </summary>
        public static string myModalVerGastoTitle {
            get {
                return ResourceManager.GetString("myModalVerGastoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NO.
        /// </summary>
        public static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Noviembre.
        /// </summary>
        public static string Noviembre {
            get {
                return ResourceManager.GetString("Noviembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Octubre.
        /// </summary>
        public static string Octubre {
            get {
                return ResourceManager.GetString("Octubre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi perfil.
        /// </summary>
        public static string OpcCambiarPass {
            get {
                return ResourceManager.GetString("OpcCambiarPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        public static string OpcCerraSession {
            get {
                return ResourceManager.GetString("OpcCerraSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string OpcLogin {
            get {
                return ResourceManager.GetString("OpcLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        public static string OpcRegistrarse {
            get {
                return ResourceManager.GetString("OpcRegistrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo gasto.
        /// </summary>
        public static string PopUpAddGasto {
            get {
                return ResourceManager.GetString("PopUpAddGasto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo gasto.
        /// </summary>
        public static string PropTipoGasto {
            get {
                return ResourceManager.GetString("PropTipoGasto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Septiembre.
        /// </summary>
        public static string Septiembre {
            get {
                return ResourceManager.GetString("Septiembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SI.
        /// </summary>
        public static string Si {
            get {
                return ResourceManager.GetString("Si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sueldo Bruto Anual.
        /// </summary>
        public static string SueldoBrutoAnual {
            get {
                return ResourceManager.GetString("SueldoBrutoAnual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de pago por defecto.
        /// </summary>
        public static string TipoPagoPorDefecto {
            get {
                return ResourceManager.GetString("TipoPagoPorDefecto", resourceCulture);
            }
        }
    }
}
